### ISSUE TITLE
What python version did you guys use for this project?

### ISSUE THREAD

**Issue by ShaysFrame** [SunLab-GMU/GraphSPD#12]
Using your script it seems that I can't install the following torch version that's been specified with cpu tag
pip install torch==1.11.0+cpu torchvision==0.12.0+cpu torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cpu

but if I change it to:
pip install torch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cpu

Then it's okay. 

The pip list:
------------------------------------------------------------------------------------------------------------------------
$ pip list
Package            Version
------------------ -----------
certifi            2022.12.7
charset-normalizer 3.4.1
clang              6.0.0.2
idna               3.10
Jinja2             3.1.5
joblib             1.3.2
MarkupSafe         2.1.5
numpy              1.21.6
pandas             1.3.5
Pillow             9.5.0
pip                22.3.1
psutil             6.1.1
pyparsing          3.1.4
python-dateutil    2.9.0.post0
pytz               2024.2
requests           2.31.0
scikit-learn       1.0.2
scipy              1.7.3
setuptools         65.6.3
six                1.17.0
threadpoolctl      3.1.0
torch              1.11.0
torch-cluster      1.6.1
torch-geometric    2.3.1
torch-scatter      2.1.1
torch-sparse       0.6.17
torch-spline-conv  1.2.2
torchaudio         0.11.0
torchvision        0.12.0
tqdm               4.67.1
typing_extensions  4.7.1
urllib3            2.0.7
wheel              0.38.4

And the error I get on the last stage.
------------------------------------------------------------------------------------------------
$ python3 test.py 
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from torch_geometric.data import Data
  File "/home/parallels/anaconda3/envs/graphspd/lib/python3.7/site-packages/torch_geometric/__init__.py", line 1, in <module>
    import torch_geometric.utils
  File "/home/parallels/anaconda3/envs/graphspd/lib/python3.7/site-packages/torch_geometric/utils/__init__.py", line 3, in <module>
    from .scatter import scatter
  File "/home/parallels/anaconda3/envs/graphspd/lib/python3.7/site-packages/torch_geometric/utils/scatter.py", line 7, in <module>
    import torch_geometric.typing
  File "/home/parallels/anaconda3/envs/graphspd/lib/python3.7/site-packages/torch_geometric/typing.py", line 37, in <module>
    import torch_sparse  # noqa
  File "/home/parallels/anaconda3/envs/graphspd/lib/python3.7/site-packages/torch_sparse/__init__.py", line 40, in <module>
    from .tensor import SparseTensor  # noqa
  File "/home/parallels/anaconda3/envs/graphspd/lib/python3.7/site-packages/torch_sparse/tensor.py", line 13, in <module>
    class SparseTensor(object):
  File "/home/parallels/anaconda3/envs/graphspd/lib/python3.7/site-packages/torch/jit/_script.py", line 1302, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/home/parallels/anaconda3/envs/graphspd/lib/python3.7/site-packages/torch/jit/_recursive.py", line 44, in _compile_and_register_class
    script_class = torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
RuntimeError: 
object has no attribute sparse_csc_tensor:
  File "/home/parallels/anaconda3/envs/graphspd/lib/python3.7/site-packages/torch_sparse/tensor.py", line 520
            value = torch.ones(self.nnz(), dtype=dtype, device=self.device())
    
        return torch.sparse_csc_tensor(colptr, row, value, self.sizes())
               ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
------------------------------------------------------------------------------------------------------------------------

I tried using different python versions such as python 3.8,9,10 and I get new different erros! for example 3.10 gives me error 

------------------------------------------------------------------------------------------------------------------------
$ python3 test.py
/home/parallels/anaconda3/envs/graphspd3.10/lib/python3.10/site-packages/torch_geometric/typing.py:86: UserWarning: An issue occurred while importing 'torch-scatter'. Disabling its usage. Stacktrace: /home/parallels/anaconda3/envs/graphspd3.10/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /home/parallels/anaconda3/envs/graphspd3.10/lib/python3.10/site-packages/torch_scatter/_version_cpu.so)
  warnings.warn(f"An issue occurred while importing 'torch-scatter'. "
/home/parallels/anaconda3/envs/graphspd3.10/lib/python3.10/site-packages/torch_geometric/typing.py:97: UserWarning: An issue occurred while importing 'torch-cluster'. Disabling its usage. Stacktrace: /home/parallels/anaconda3/envs/graphspd3.10/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /home/parallels/anaconda3/envs/graphspd3.10/lib/python3.10/site-packages/torch_cluster/_version_cpu.so)
  warnings.warn(f"An issue occurred while importing 'torch-cluster'. "
/home/parallels/anaconda3/envs/graphspd3.10/lib/python3.10/site-packages/torch_geometric/typing.py:113: UserWarning: An issue occurred while importing 'torch-spline-conv'. Disabling its usage. Stacktrace: /home/parallels/anaconda3/envs/graphspd3.10/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /home/parallels/anaconda3/envs/graphspd3.10/lib/python3.10/site-packages/torch_spline_conv/_version_cpu.so)
  warnings.warn(
/home/parallels/anaconda3/envs/graphspd3.10/lib/python3.10/site-packages/torch_geometric/typing.py:124: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: /home/parallels/anaconda3/envs/graphspd3.10/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /home/parallels/anaconda3/envs/graphspd3.10/lib/python3.10/site-packages/torch_sparse/_version_cpu.so)
  warnings.warn(f"An issue occurred while importing 'torch-sparse'. "
Traceback (most recent call last):
  File "/home/parallels/researchfolder/GraphSPD/test.py", line 6, in <module>
    from torch_geometric.data import Data
  File "/home/parallels/anaconda3/envs/graphspd3.10/lib/python3.10/site-packages/torch_geometric/__init__.py", line 8, in <module>
    from .index import Index
  File "/home/parallels/anaconda3/envs/graphspd3.10/lib/python3.10/site-packages/torch_geometric/index.py", line 461, in <module>
    @implements(aten.clone.default)
AttributeError: 'builtin_function_or_method' object has no attribute 'default'

------------------------------------------------------------------------------------------------------------------------

So at this point I'm doubting maybe it's because of the modified line I've done in the script which is as follows:

sudo ln -s /usr/lib/aarch64-linux-gnu/libclang-*.so.1 /usr/lib/aarch64-linux-gnu/libclang.so

since i'm on arm based mac needed to modify the link... 

but what's this mess.... @ . @

**Comment by ShaysFrame** [comment]
also now getting another issue which is 

(gspd) shay@Shays-Mackbook GraphSPD % python3 test.py 
zsh: segmentation fault  python3 test.py
