### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by klssstis** [SunLab-GMU/GraphSPD#4]
Good afternoon.
I tried running a clean `Ubuntu 20.04.4` docker image (`ubuntu:focal-20220302`).
and ran into an error, could you help me. (`python3 test.py`)

Thank you.

p.s. same error in `google collab`

```
root@43e82c91b137:~/GraphSPD# python3 test.py
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from torch_geometric.data import Data
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/__init__.py", line 1, in <module>
    import torch_geometric.utils
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/utils/__init__.py", line 3, in <module>
    from .scatter import scatter
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/utils/scatter.py", line 7, in <module>
    import torch_geometric.typing
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/typing.py", line 37, in <module>
    import torch_sparse  # noqa
  File "/usr/local/lib/python3.8/dist-packages/torch_sparse/__init__.py", line 40, in <module>
    from .tensor import SparseTensor  # noqa
  File "/usr/local/lib/python3.8/dist-packages/torch_sparse/tensor.py", line 13, in <module>
    class SparseTensor(object):
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_script.py", line 1302, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_recursive.py", line 44, in _compile_and_register_class
    script_class = torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
RuntimeError:
object has no attribute sparse_csc_tensor:
  File "/usr/local/lib/python3.8/dist-packages/torch_sparse/tensor.py", line 520
            value = torch.ones(self.nnz(), dtype=dtype, device=self.device())

        return torch.sparse_csc_tensor(colptr, row, value, self.sizes())
               ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
```

**Comment by klssstis** [comment]
the problem was:
`torch-sparse 0.6.17`
`torch-geometric 2.3.1`

I changed them.

maybe someone will be useful.

```
FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install -y git python3 sudo
WORKDIR /root/
##RUN git clone https://github.com/SunLab-GMU/GraphSPD.git
RUN git clone https://github.com/klssstis/GraphSPD.git
WORKDIR /root/GraphSPD/
RUN chmod +x install_dep.sh
RUN ./install_dep.sh
RUN python3 get_ab_file.py nginx nginx 02cca547
RUN python3 get_ab_file.py nginx nginx 661e4086
RUN python3 get_ab_file.py nginx nginx 9a3ec202
RUN python3 get_ab_file.py nginx nginx dac90a4b
RUN python3 get_ab_file.py nginx nginx fc785b12
RUN python3 get_ab_file.py nginx nginx 60a8ed26
RUN python3 get_ab_file.py nginx nginx bd7dad5b
RUN python3 get_ab_file.py nginx nginx 4c5a49ce
RUN python3 get_ab_file.py nginx nginx 71eb19da
RUN python3 get_ab_file.py nginx nginx 56f53316
RUN chmod -R +x ./joern
RUN sudo python3 gen_cpg.py
RUN python3 merge_cpg.py
RUN python3 test.py
CMD cat logs/test_results.txt

```
